#!/usr/bin/env python
#-------------------------------------------------------------------------------
# test/run_readelf_tests.py
#
# Automatic test runner for elftools & readelf
#
# Eli Bendersky (eliben@gmail.com)
# This code is in the public domain
#-------------------------------------------------------------------------------

from __future__ import annotations

import os
import platform
from contextlib import suppress
from difflib import SequenceMatcher
from pathlib import Path
from subprocess import run

import pytest


# Set the path for calling readelf. We carry our own version of readelf around,
# because binutils tend to change its output even between daily builds of the
# same minor release and keeping track is a headache.
if platform.system() == "Darwin": # MacOS
    READELF_PATH = 'greadelf'
elif platform.system() == "Windows":
    # Point the environment variable READELF at Cygwin's readelf.exe, or some other Windows build
    READELF_PATH = os.environ.get('READELF', "readelf.exe")
elif platform.system() != "Linux":
    pytest.skip(reason=f"Platform {platform.system()!r} not supported")
else:
    READELF_PATH = 'test/external_tools/readelf'
    if not os.path.exists(READELF_PATH):
        READELF_PATH = 'readelf'


def pytest_generate_tests(metafunc: pytest.Metafunc) -> None:
    filelist = Path("test/testfiles_for_readelf").glob("*.elf")
    metafunc.parametrize("testpath", filelist, ids=lambda path: path.stem)


@pytest.mark.parametrize("option", [
    '-e',  # --headers
    '-d',  # --dynamic
    '-s',  # --syms
    '-n',  # --notes
    '-r',  # --relocs
    '-x.text',  # --hex-dump=
    '-p.shstrtab',  # --string-dump=
    '-V',  # --version-info
    '--debug-dump=info',
    '--debug-dump=decodedline',
    '--debug-dump=frames',
    '--debug-dump=frames-interp',
    '--debug-dump=aranges',
    '--debug-dump=pubtypes',
    '--debug-dump=pubnames',
    '--debug-dump=loc',
    '--debug-dump=Ranges',
    '--arch-specific',
])
def test_dwarfdump(testpath: Path, option: str) -> None:
    if testpath.name.endswith('dwarf_debug_types.elf'):
        # TODO: excluding the binary with .debug_types section until the length
        #  the calculation for FDEs in binutils bug #31973 is fixed
        #  https://sourceware.org/bugzilla/show_bug.cgi?id=31973
        if option in {"--debug-dump=frames", "--debug-dump=frames-interp", "--debug-dump=aranges"}:
            pytest.skip("Skip combination")
        # TODO: Stream parsing errors out with the .debug_aranges section
        #  generated by IAR EWARM 9.20.4.
        # https://github.com/STMicroelectronics/STM32CubeWB/issues/109
    if "core" in testpath.name and option in {"-n", "--notes"}:
        # TODO(zlobober): this is a dirty hack to make tests work for ELF core
        # dump notes. Making it work properly requires a pretty deep
        # investigation of how original readelf formats the output.
        pytest.skip("Not implemented in readelf.py yet")
    if "dwarf_v4cie" in testpath.name and option == "--debug-dump=frames-interp":
        # TODO(sevaa): excluding the binary with CIE ahead of FDE until binutils' bug #31975 is fixed
        pytest.skip("Waiting for #31975")
    if "dwarf_v4cie" in testpath.name and option == "--debug-dump=aranges":
        # TODO(sevaa): excluding the binary with unaligned aranges entries. Readelf tried to recover
        # but produces nonsensical output, but ultimately it's a toolchain bug (in IAR I presume).
        pytest.skip("Unaligned aranges")
    if "-eabi-" not in testpath.name and option in {"-A", "--arch-specific"}:
        # TODO(pmhahn): for now only ARM works
        pytest.skip("Only for ARM")

    # sevaa says: there is another shorted out test; in dwarf_lineprogramv5.elf, the two bytes at 0x2072 were
    # patched from 0x07 0x10 to 00 00.
    # Those represented the second instruction in the first FDE in .eh_frame. This changed the instruction
    # from "DW_CFA_undefined 16" to two NOPs.
    # GNU readelf 2.38 had a bug here, had to work around:
    # https://sourceware.org/bugzilla/show_bug.cgi?id=29250
    # It's been fixed in the binutils' master since, but the latest master will break a lot.
    # Same patch in  dwarf_test_versions_mix.elf at 0x2061: 07 10 -> 00 00

    env = dict(os.environ, LC_ALL="C")
    native, python = (
        run(
            [exe_path, option, testpath],
            capture_output=True,
            timeout=600,
            check=True,
            text=True,
            env=env,
        ).stdout
        for exe_path in [READELF_PATH, 'scripts/readelf.py']
    )

    nlines, plines = (
        [line for line in s.lower().splitlines() if line.strip()]
        for s in (native, python)
    )

    assert len(nlines) == len(plines), \
        f'Number of lines different: {len(nlines)} vs {len(plines)}'

    # Note: this function contains some rather horrible hacks to ignore
    # differences which are not important for the verification of pyelftools.
    # This is due to some intricacies of binutils's readelf which pyelftools
    # doesn't currently implement, features that binutils doesn't support,
    # or silly inconsistencies in the output of readelf, which I was reluctant
    # to replicate. Read the documentation for more details.

    flag_in_debug_line_section = False

    # Position of the View column in the output file, if parsing readelf..decodedline
    # output, and the GNU readelf output contains the View column. Otherwise stays -1.
    view_col_position = stmt_col_position = -1

    for i, (nline, pline) in enumerate(zip(nlines, plines, strict=True)):
        # .debug_line or .zdebug_line
        flag_in_debug_line_section |= nline.endswith('debug_line section:')

        # readelf spelling error for GNU property notes
        nline = nline.replace('procesor-specific type', 'processor-specific type')

        # The view column position may change from CU to CU:
        if view_col_position >= 0 and nline.startswith('cu:'):
            view_col_position = -1

        # Check if readelf..decodedline output line contains the view column
        if flag_in_debug_line_section and nline.startswith('file name') and view_col_position < 0:
            view_col_position = nline.find("view")
            stmt_col_position = nline.find("stmt")

        # Excise the View column from the table, if any.
        # View_col_position is only set to a nonzero number if one of the previous
        # lines was a table header line with a "view" in it.
        # We assume careful formatting on GNU readelf's part - View column values
        # are not out of line with the View header.
        if view_col_position >= 0 and not nline.endswith(':'):
            nline = nline[:view_col_position] + nline[stmt_col_position:]

        # Compare ignoring whitespace
        nparts = nline.split()
        pparts = pline.split()
        if ''.join(nparts) == ''.join(pparts):
            continue

        *nhead, ntail = nparts
        *phead, ptail = pparts

        # Ignore difference in precision of hex representation in the
        # last part (i.e. 008f3b vs 8f3b)
        with suppress(ValueError):
            if ''.join(nhead) == ''.join(phead) and int(ntail, 16) == int(ntail, 16):
                continue

        # Special case truncations with ellipsis like these:
        #     .note.gnu.bu[...]        redelf
        #     .note.gnu.build-i        pyelftools
        # Or more complex for symbols with versions, like these:
        #     _unw[...]@gcc_3.0        readelf
        #     _unwind_resume@gcc_3.0   pyelftools
        if '[...]' in nline and all(
            len(np) <= len(pp) and pp.startswith(nh) and pp.endswith(nt)
            for ((nh, _, nt), np, pp) in (
                (np.partition("[...]"), np, pp)
                for np, pp in zip(nparts, pparts, strict=True)
            )
        ):
            continue

        # On 32-bit machines, readelf doesn't correctly represent
        # some boundary LEB128 numbers
        if 'at_const_value' in nline:
            num2 = int(ptail, 16 if ptail.startswith('0x') else 10)
            if num2 <= -2**31 and '32' in platform.architecture()[0]:
                continue

        if 'os/abi' in nline and 'unix - gnu' in nline and 'unix - linux' in pline:
            continue

        # readelf does not seem to print a readable description for this
        if len(nparts) == 3 and nparts[2] == 'nt_gnu_property_type_0' and nparts == pparts[:3]:
            continue

        if any(s in nline or s in pline for s in ('t (tls)', 'l (large)', 'd (mbind)')):
            continue

        assert False, f'Mismatch on line #{i}:\n>>{nline}<<\n>>{pline}<<\n ({SequenceMatcher(a=nline, b=pline).get_opcodes()!r})'
